add_library(
    openlegend_ui
    STATIC
        basic_ui_renderer.cpp
        game_menu.cpp
        new_game_attributes.cpp
        new_game_name_editor.cpp
        title_menu.cpp
)
target_include_directories(
    openlegend_ui
    PUBLIC
        $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:include>
)
target_link_libraries(
    openlegend_ui
    PUBLIC
        openlegend_model
        openlegend_render
        openlegend_resource
        openlegend_project_options
        openlegend_project_warnings
)
