#!/usr/bin/env python3
"""Generate the deterministic Unicode-to-Big5 table used by OpenLegend."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re

SOURCE_URL = (
    "https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP950.TXT"
)
SOURCE_SHA256 = "ed403857b05e07ecd5667c7eff6b25898cb1fefe2d06cfe718d82d631e6058b6"
EXPECTED_ROWS = 13_503
EXPECTED_UNICODE_CHARACTERS = 13_493
CANONICAL_OVERRIDES = {
    0x5341: 0xA451,
    0x5345: 0xA4CA,
}
MAPPING_PATTERN = re.compile(r"^0x([0-9A-Fa-f]+)\s+0x([0-9A-Fa-f]+)")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    return parser.parse_args()


def valid_double_byte_code(code: int) -> bool:
    lead = code >> 8
    trail = code & 0xFF
    return (
        0xA1 <= lead <= 0xF9
        and (0x40 <= trail <= 0x7E or 0xA1 <= trail <= 0xFE)
    )


def load_mappings(source: pathlib.Path) -> list[tuple[int, int]]:
    source_bytes = source.read_bytes()
    source_hash = hashlib.sha256(source_bytes).hexdigest()
    if source_hash != SOURCE_SHA256:
        raise ValueError(
            f"unexpected CP950 source SHA-256: {source_hash}; expected {SOURCE_SHA256}"
        )

    mappings: list[tuple[int, int]] = []
    for line in source_bytes.decode("ascii").splitlines():
        match = MAPPING_PATTERN.match(line)
        if match is None:
            continue
        code = int(match.group(1), 16)
        code_point = int(match.group(2), 16)
        if valid_double_byte_code(code):
            mappings.append((code_point, code))

    if len(mappings) != EXPECTED_ROWS:
        raise ValueError(
            f"unexpected CP950 double-byte row count: {len(mappings)}; "
            f"expected {EXPECTED_ROWS}"
        )
    return mappings


def canonicalize(mappings: list[tuple[int, int]]) -> list[tuple[int, int]]:
    candidates: dict[int, list[int]] = {}
    for code_point, code in mappings:
        candidates.setdefault(code_point, []).append(code)

    canonical: list[tuple[int, int]] = []
    for code_point, codes in candidates.items():
        if code_point > 0xFFFF:
            raise ValueError(f"non-BMP CP950 mapping: U+{code_point:06X}")
        code = CANONICAL_OVERRIDES.get(code_point, codes[0])
        if code not in codes:
            raise ValueError(
                f"canonical code 0x{code:04X} is not a candidate for U+{code_point:04X}"
            )
        canonical.append((code_point, code))

    canonical.sort()
    if len(canonical) != EXPECTED_UNICODE_CHARACTERS:
        raise ValueError(
            f"unexpected unique Unicode count: {len(canonical)}; "
            f"expected {EXPECTED_UNICODE_CHARACTERS}"
        )
    return canonical


def render(mappings: list[tuple[int, int]]) -> str:
    lines = [
        "// Generated by tools/generate_big5_mapping.py; do not edit.",
        f"// Source: {SOURCE_URL}",
        f"// Source SHA-256: {SOURCE_SHA256}",
        "// Mapping data copyright Unicode, Inc.; see https://www.unicode.org/license.txt.",
        "// Values pack U+XXXX in the high word and canonical CP950 Big5 in the low word.",
    ]
    for start in range(0, len(mappings), 6):
        entries = ", ".join(
            f"0x{code_point:04X}{code:04X}U"
            for code_point, code in mappings[start : start + 6]
        )
        lines.append(f"    {entries},")
    return "\n".join(lines) + "\n"


def main() -> None:
    arguments = parse_arguments()
    mappings = canonicalize(load_mappings(arguments.source))
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(render(mappings), encoding="ascii", newline="\n")
    print(f"generated {len(mappings)} mappings: {arguments.output}")


if __name__ == "__main__":
    main()
